package com.example.tubes01e;

public enum FragmentType{
    FRAGMENT_HOME, FRAGMENT_RANDOM_SEARCH, FRAGMENT_SETTING, FRAGMENT_ADD_MENU, FRAGMENT_EDIT_MENU, FRAGMENT_MENU_DETAIL, FRAGMENT_MENU_LIST
}
